//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neigh.Datamodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class neighEntities : DbContext
    {
        public neighEntities()
            : base("name=neighEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Horse> Horses { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Show_Judges> Show_Judges { get; set; }
        public virtual DbSet<Show> Shows { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Results_Show_Judges> Results_Show_Judges { get; set; }
    }
}
