//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neigh.Datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show_Judges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Show_Judges()
        {
            this.Results_Show_Judges = new HashSet<Results_Show_Judges>();
        }
    
        public int Id { get; set; }
        public int ShowId { get; set; }
        public string Name { get; set; }
    
        public virtual Show Show { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results_Show_Judges> Results_Show_Judges { get; set; }
    }
}
